name: freezer-id

services:
  db:
    image: postgres:16.4-alpine
    restart: always
    environment:
      POSTGRES_USER: freezer-id
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db:5432
