version: '3.8'
name: freezer-id

services:
  database:
    image: postgres
    restart: always
    env_file:
      - ../../stack.env
    ports:
      - "5432"
    volumes:
      - /freezer-id/database/data:/var/lib/postgresql/data
  webapp:
    depends_on:
      - database
    image: ghcr.io/lukehollanddev/freezerid:main
    restart: always
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate dev && npm run start"
