version: '3.8'
name: freezer-id

services:
  database:
    image: postgres
    restart: always
    env_file:
      - ../../stack.env
    ports:
      - "5432"
  webapp:
    depends_on:
      - database
    build:
      context: ../../freezer-id
      dockerfile: ../docker/production/Dockerfile
    image: freezer-id-webapp
    ports:
      - '3001:3000'
    env_file:
      - ../../stack.env
    command: sh -c "npx prisma migrate dev && npm run start"
