name: Build and Push Docker Image

on:
    push:
        branches:
            - main

env:
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@database:5432/freezer-id?schema=public
    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
    GOOGLE_SECRET_ID: ${{ secrets.GOOGLE_SECRET_ID }}
    NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
    VIRTUAL_HOST: freezer.lukeholland.dev

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v5
              with:
                  context: ./freezer-id
                  file: ./docker/production/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                    "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
                    "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
                    "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@database:5432/freezer-id?schema=public"
                    "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}"
                    "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}"
                    "GOOGLE_SECRET_ID=${{ secrets.GOOGLE_SECRET_ID }}"
                    "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}"
                    "VIRTUAL_HOST=freezer.lukeholland.dev"